package test.yhc.ytdn;
public enum Err {
    NO_ERR,
    UNKNOWN,
    INTERRUPTED,
    CANCELLED,
    MULTITHREADING,
    NETWORK_UNAVAILABLE,
    IO_NET,
    IO_FILE,
    IO_UNKNOWN,
    DB_DUPLICATED,
    DB_VERSION_MISMATCH,
    DB_NODATA,
    DB_INVALID,
    DB_UNKNOWN,
    INVALID_URL,
    PARSER_UNEXPECTED_FORMAT,
    PARSER_UNKNOWN,
    NO_MATCH,
    YTSEARCH,
    YTHTTPGET,
    END_OF_DATA;
}
